version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    volumes:
      - ./backend:/app

  consumer:
    build:
      context: ./backend
      dockerfile: Dockerfile.consumer
    depends_on:
      - rabbitmq
    volumes:
      - ./backend:/app
    restart: unless-stopped
